---
# handlers file for postfix

- name: rebuild alias database
  command: postmap "{{ postfix_alias_path }}"

- name: rebuild sender_access database
  command: postmap "{{ postfix_sender_access_path }}"

- name: rebuild recipient_access database
  command: postmap "{{ postfix_recipient_access_path }}"

- name: restart postfix
  ansible.builtin.service:
    name: "{{ postfix_service }}"
    state: restarted
  when:
    - not ansible_check_mode | bool
