---
- name: Converge
  hosts: all
  become: true
  gather_facts: false

  vars:
    postfix_aliases:
      - name: root
        destination: robert@meinit.nl

  roles:
    - robertdebock.bootstrap
    - ansible-role-postfix
